AC_PREREQ
AC_INIT([leetcode], [1.0], [kdillo893@gmail.com])
AM_INIT_AUTOMAKE([-Wall -Werror foreign])

# AC_CONFIG_SRCDIR([src/leetcode.c])
AC_CONFIG_HEADERS([config.h])
AC_CONFIG_FILES([Makefile]) 

#program flags for checking we have these in path
AC_PROG_AWK
AC_PROG_CC
# AC_PROG_CPP
# AC_PROG_INSTALL
# AC_PROG_LN_S
#check for the linking of the library included
# AC_CHECK_LIB()

#validate that headers and functions are included in compilation
AC_CHECK_HEADER_STDBOOL
# AC_CHECK_HEADERS([])
# AC_CHECK_FUNCS([])
AC_OUTPUT
